# 菜单路径
menu:
  home: /
  archives: archives
  tags: tags
  about: about
  search: search


# site title 
# 页面标题
# title为空时 Hexo/_config.yml 配置有效
title: 

# author profile
# 作者信息
# author为空时 Hexo/_config.yml 配置有效
profile: 
  author: 
  avatar: /images/avatar.png  
  description: 

# site favicon
# 站点图标
favicon: /images/favicon.png


# social link
social:  
  Github: https://github.com/muzhidong 
  Juejin: https://juejin.im/user/57dbd39967f35600569b20c8 
# Weibo:
# Zhihu:
# Facebook:
# Twitter:
# Instagram:
# LinkedIn:
  

# toc
# 文章的目录 
toc: true
  

# site analytics 
# 站点访问统计
umeng_analytics: true
# baidu_analytics: 
#google_analytics: 


# comment

# disqus(https://disqus.com/)
disqus:
  comment: false
  shortname: 

# valine(https://github.com/xCss/Valine)
# 创建 leancloud 应用 获取 id|key 填入即可
leancloud:  
  comment: false
  app_id: 
  app_key: 


# mob share(http://www.mob.com)
# 文章分享功能
mob_share: true

share_item:
- qq
- weixin
- weibo
#- douban
#- facebook
#- twitter
#- tumblr
#- google


# donate
# 捐赠功能
# source/imgaes/
donate:
  enable: true
  word: 觉得不错就赞赏一下吧
  alipay: /images/alipay.png
  wechat: /images/wechat.png  


# mathjax 
# 渲染LateX公式
# 在post文章头部添加:
#   mathjax: true
# 即可在当前post开启mathjax
mathjax:
  enable: true
  

# excerpt_ignore [boolean]
# 在文章头部中增加此配置 
# 文章是否需要显示摘要 默认为显示


# footer
# 底部信息
footer:
  author: greatApe
  since: 2018.07


# theme version
version: 1.0.0